/** Silver & Wave Pro — light palette */
export const designLightColors = {
  surface: "#f8f9ff",
  surfaceDim: "#cbdbf5",
  surfaceBright: "#f8f9ff",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#eff4ff",
  surfaceContainer: "#e5eeff",
  surfaceContainerHigh: "#dce9ff",
  surfaceContainerHighest: "#d3e4fe",
  onSurface: "#0b1c30",
  onSurfaceVariant: "#3c4a40",
  outline: "#6c7b6f",
  outlineVariant: "#bbcabd",
  surfaceTint: "#006d41",
  primary: "#006d41",
  onPrimary: "#ffffff",
  primaryContainer: "#00c076",
  onPrimaryContainer: "#004728",
  secondary: "#516072",
  secondaryContainer: "#d2e1f7",
  onSecondaryContainer: "#556477",
  tertiary: "#595f66",
  error: "#ba1a1a",
  errorContainer: "#ffdad6",
  background: "#f8f9ff",
  onBackground: "#0b1c30",
  surfaceVariant: "#d3e4fe",
  warning: "#b45309",
} as const;
