/** Obsidian Financial Pro — light palette (Professional Dashboard) */
export const designLightColors = {
  surface: "#f7f9fb",
  surfaceDim: "#d8dadc",
  surfaceBright: "#f7f9fb",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#f2f4f6",
  surfaceContainer: "#eceef0",
  surfaceContainerHigh: "#e6e8ea",
  surfaceContainerHighest: "#e0e3e5",
  onSurface: "#191c1e",
  onSurfaceVariant: "#3c4a40",
  outline: "#6c7b6f",
  outlineVariant: "#bbcabd",
  surfaceTint: "#006d41",
  primary: "#006d41",
  onPrimary: "#ffffff",
  primaryContainer: "#00c076",
  onPrimaryContainer: "#004728",
  secondary: "#565e74",
  secondaryContainer: "#dae2fd",
  onSecondaryContainer: "#5c647a",
  tertiary: "#515f74",
  error: "#ba1a1a",
  errorContainer: "#ffdad6",
  background: "#f7f9fb",
  onBackground: "#191c1e",
  surfaceVariant: "#e0e3e5",
  warning: "#b45309",
} as const;
